name: Publish to PyPI

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install build tools
        run: pip install build twine
      - name: Make release.sh executable
        run: chmod +x scripts/release.sh
      - name: Run release script
        run: scripts/release.sh --repository-url https://upload.pypi.org/legacy/
        env:
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
